# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "maze-unstable-${version}";
  version = "2017-10-22";
  rev = "7841c955cd6ce5a74d661b9dd84a4de25dd09eba";

  goPackagePath = "github.com/weberc2/maze";

  src = fetchgit {
    inherit rev;
    url = "git@github.com-weberc2:weberc2/maze.git";
    sha256 = "1cax81gd89nscdazh0nn4xbrspb1dywws2030pi5phmd8yck8a4q";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
