# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/gorilla/context";
    fetch = {
      type = "git";
      url = "https://github.com/gorilla/context";
      rev = "1c83b3eabd45b6d76072b66b746c20815fb2872d";
      sha256 = "1bmnhsbn9wfv14mlv69c30ppjm614h1nsdgy35p4gs3kjl6srkcb";
    };
  }
  {
    goPackagePath = "github.com/gorilla/mux";
    fetch = {
      type = "git";
      url = "https://github.com/gorilla/mux";
      rev = "ee1815431e497d3850809578c93ab6705f1a19f7";
      sha256 = "1slxmhjs4w0c5b4cl6b9d9lmfps0znyh0prz14vaa23zr57f2g9s";
    };
  }
  {
    goPackagePath = "github.com/gorilla/websocket";
    fetch = {
      type = "git";
      url = "https://github.com/gorilla/websocket";
      rev = "a68708917c6a4f06314ab4e52493cc61359c9d42";
      sha256 = "0763bk55dfl11zq0w08gwng2zgvy0qaqgbvhv790cz9q4ah6514x";
    };
  }
  {
    goPackagePath = "github.com/itchyny/maze";
    fetch = {
      type = "git";
      url = "https://github.com/itchyny/maze";
      rev = "0f18dca8c6366c20f6784a6263b14a92fffeaa15";
      sha256 = "0jkff50hgq284gr7i04c4cl89383n9jpb93k1675zw1bzyd4zqzf";
    };
  }
  {
    goPackagePath = "github.com/kr/pretty";
    fetch = {
      type = "git";
      url = "https://github.com/kr/pretty";
      rev = "cfb55aafdaf3ec08f0db22699ab822c50091b1c4";
      sha256 = "0441yi9ah9892hxdslv2h35bkfr75g7ajma0q45lqks84pawrdkg";
    };
  }
  {
    goPackagePath = "github.com/kr/text";
    fetch = {
      type = "git";
      url = "https://github.com/kr/text";
      rev = "7cafcd837844e784b526369c9bce262804aebc60";
      sha256 = "0br693pf6vdr1sfvzdz6zxq7hjpdgci0il4wj0v636r8lyy21vsx";
    };
  }
]
